remote_theme: pages-themes/minimal
title: Ozias OROU YAWA
description: "Géographe-Écologue | Expert SIG & Analyse de données spatiales"
# Liens qui apparaîtront dans la barre latérale
google_analytics: 
show_downloads: false
